### ISSUE TITLE
Footer appears twice

### ISSUE THREAD

**Issue by klyrr** [Tradeshift/tradeshift-ui#444] opened 2017-11-17 16:13 UTC
#### Tradeshift UI version affected
v9.3.2

#### Expected Behavior
Footer shows up once

#### Actual Behavior
Footer shows up twice

#### Steps to reproduce
Add the following
```
const buttons = ts.ui.Footer.buttons();
buttons.push(
	{
		label: t('Click me'),
		type: 'ts-primary'
	}
);
```

![screen shot 2017-11-17 at 15 49 11](https://user-images.githubusercontent.com/1024500/32956598-7a9cb2e0-cbb9-11e7-86fc-9be7e1fc36c4.png)
-------------

@wiredearp says the current work around is
```
const buildFooter = () => {
	const buttons = ts.ui.Footer.buttons();
	buttons.push(
		{
			label: t('Click me'),
			type: 'ts-primary'
		}
	);
};

ts.ui.ready(buildFooter);
```
It fixed the problem for me.

**Comment by klyrr** [comment] 2017-11-21 14:49
If I understand this correctly the problem is that the `ts-footerbar-bufferbar` is visible which is an error according to https://github.com/Tradeshift/tradeshift-ui/blob/master/src/runtime/js/ts.ui/bars/bars-gui@tradeshift.com/spirits/footer/ts.ui.FooterBarSpirit.js#L326

**Comment by klyrr** [comment] 2017-11-21 15:15
I "fixed" it at the moment with 
```
.ts-footerbar-bufferbar {
	display: none;
}
```
here https://github.com/Tradeshift/Apps/pull/6182

**Comment by wiredearp** [comment] 2017-11-21 16:10
@klyrr Didn’t the `ts.ui.ready` work around it already? The purpose of the bufferbar is to measure the dimension of elements and that will certainly not work when they are display none, so I suggest that this is the least desired workaround. If it doesn’t break (make sure to check Firefox], it at least only works because you only have one button and nothing else in the Footer.

**Comment by klyrr** [comment] 2017-11-22 09:07
No. Unfortunately not. 

This is my code:
```

const BottomBar = ({
	canSubmitForApproval = false,
	showApprovalButtons = false,
	showAssistanceButton = false,
	showAssistanceDoneButton = false,
	isAssistanceNeeded = false,
	isSubmitForApprovalBusy = false,
	assistanceSubmitted = false,
	onShare = () => {},
	onSubmit = () => {},
	onApprove = () => {},
	onReject = () => {},
	onAssistance = () => {},
	onAssistanceDone = () => {}
}) => {
	const buildFooter = () => {
		const buttons = ts.ui.Footer.buttons();

		// we must add the buttons only once
		if (buttons.get(SUBMIT_FOR_APPROVAL_ID)) {
			return;
		}

		ts.ui.Footer.collabbutton(onShare);
		buttons.push(
			createSubmitForApprovalButton(),
			createRejectButton(),
			createApproveButton(),
			createSubmitForAssistanceButton(),
			createReturnToRequesterlButton()
		);
	};

	ts.ui.ready(buildFooter);

	const buttons = ts.ui.Footer.buttons();
	if (buttons.get(SUBMIT_FOR_APPROVAL_ID)) {
		buttons.get(SUBMIT_FOR_APPROVAL_ID).onclick = onSubmit;
		buttons.get(REJECT_ID).onclick = onReject;
		buttons.get(APPROVE_ID).onclick = onApprove;
		buttons.get(SUBMIT_FOR_ASSISTANCE_ID).onclick = onAssistance;
		buttons.get(RETURN_TO_REQUESTER_ID).onclick = onAssistanceDone;

		buttons.get(SUBMIT_FOR_APPROVAL_ID).visible = canSubmitForApproval;
		buttons.get(REJECT_ID).visible = showApprovalButtons;
		buttons.get(APPROVE_ID).visible = showApprovalButtons;
		buttons.get(SUBMIT_FOR_ASSISTANCE_ID).visible = showAssistanceButton;
		buttons.get(RETURN_TO_REQUESTER_ID).visible = showAssistanceDoneButton;

		buttons.get(SUBMIT_FOR_ASSISTANCE_ID).disabled = assistanceSubmitted;
		buttons.get(RETURN_TO_REQUESTER_ID).disabled = assistanceSubmitted || isAssistanceNeeded;
	}

	return null;
};
```

So. I build the footer once. But I have to set the `visible` and `disabled` properties according to the react state.

And once I call the function `const buttons = ts.ui.Footer.buttons();` again I get the second row again. Although the other call is called in the `ready` function.

And Yes. I admit this is not good.

Hmm.. Maybe I should change this to a "real" react component and update the status during the component lifecycle. Ok. I'll try that. And update the ticket :)

**Comment by klyrr** [comment] 2017-11-22 09:46
as soon as I put `const buttons = ts.ui.Footer.buttons()` in the render function I get two footers.

**Comment by klyrr** [comment] 2017-11-22 10:05
ok. I found the solution. I'll link my PR once I am done.

**Comment by klyrr** [comment] 2017-11-22 11:56
I fixed it with calling the update for the buttons in the `componentWillReceiveProps` function. As soon as I call this in the render function I have to footers.

See the code [here](https://github.com/Tradeshift/Apps/pull/6182/files#diff-706d42612eca0d4c1f4e2aaea3785efd)

**Comment by wiredearp** [comment] 2017-11-22 12:19
Right. Sorry about the bug 😢

**Comment by klyrr** [comment] 2017-11-22 13:13
As long as you fix it ;)

**Comment by zdlm** [comment] 2019-01-09 09:14
Fixed in V12. Can't reproduce it again.

**Closed by zdlm** 2019-01-09 09:14 UTC
Labels: issue: bug
