### ISSUE TITLE
[Pager] content defined in css display incorrectly

### ISSUE THREAD

**Issue by Chris-Xie** [Tradeshift/tradeshift-ui#417] opened 2017-10-25 08:29 UTC
#### Tradeshift UI version affected
v9.2.4

#### Expected Behavior
<img width="453" alt="screen shot 2017-10-25 at 16 26 33" src="https://user-images.githubusercontent.com/5295157/31988348-601ceefe-b934-11e7-93cb-c8f9f7357589.png">

#### Actual Behavior
![2341508917552_ pic](https://user-images.githubusercontent.com/5295157/31988374-74d3d678-b934-11e7-856c-9cba3beeb1fd.jpg)

#### Steps to reproduce
Hard to reproduce (it happens occasionally), but if you open http://d5wfroyti11sa.cloudfront.net/prod/client/ts-9.2.4.min.css in your browser directly, and search for ".ts-pager menu li button.ts-more span:after{" and you would notice that the content is incorrect. 

I believe that we should use unicode instead.

**Comment by wiredearp** [comment] 2017-10-25 09:58
@Chris-Xie That is unicode :disappointed:

Duplicate of https://github.com/Tradeshift/tradeshift-ui/issues/410

**Closed by wiredearp** 2017-10-25 09:58 UTC

**Comment by wiredearp** [comment] 2017-10-25 10:05
@Chris-Xie Thanks! That fixed it.
