### ISSUE TITLE
[Aside] ts-asidecover resides on the page 

### ISSUE THREAD

**Issue by vvvts** [Tradeshift/tradeshift-ui#88] opened 2016-12-08 14:16 UTC
In Tradeshift.Search app
1. Open offer page
2. Open collaboration panel with option aside
3. Click 'back' browser button
The div '.ts-asidecover' stays and blocks everything.

[aside.zip](https://github.com/Tradeshift/tradeshift-ui/files/639630/aside.zip)

**Comment by zdlm** [comment] 2017-03-17 09:47
@sqren You can track the issue here

**Comment by wiredearp** [comment] 2017-03-20 09:22
@vvvts and @sqren: I have a question. The problem is basically that the Aside disappears but the cover remains. But it seems our code is already prepared for this scenario: When an open Aside is removed from the document, it notifies the cover; and if it was the last remaining Aside, the cover will be removed. Since this mechanism appears to be working correctly on my machine :tm:, we can speculate that you guys don't actually *remove* the Aside from the DOM, but instead you `ng-hide` it with `display:none`. Is that correct?

**Comment by sqren** [comment] 2017-03-20 14:10
> we can speculate that you guys don't actually remove the Aside from the DOM, but instead you ng-hide it with display:none. Is that correct?

I just double-checked, and the container holding all the asides (`div.panels.Tradeshift.<appName>`) is removed from the DOM when navigating away, however its sibling `.ts-cover` with attribute `data-ts-spirit="ts.ui.CoverSpirit"` is not.

**Comment by wiredearp** [comment] 2017-03-20 14:49
@sqren In that case, we have a real bug and we will fix it for real. The cover is never supposed to be removed, by the way, it is just supposed to be hidden. Thanks for the feedback.

**Comment by sqren** [comment] 2017-03-20 14:55
> The cover is never supposed to be removed, by the way, it is just supposed to be hidden

What about an API for closing it then?

**Comment by wiredearp** [comment] 2017-03-20 15:24
This wouldn't make sense once the bug is fixed, because there already is an API for hiding the cover ("close all the Asides to hide the cover'). If you override this manually, you will also ruin it for the API to show the cover ("open an aside to show the cover"). In other words, the cover is bound to the state of Asides and the problem only exists because we are not correctly tracking the state of Asides.

**Closed** 2017-03-28 10:55 UTC
Labels: bug
