### ISSUE TITLE
Table component stops working at around 60.000 entries

### ISSUE THREAD

**Issue by upphiminn** [Tradeshift/tradeshift-ui#330] opened 2017-07-28 09:57 UTC
Table component does not render when entry number exceeded the max call stack size for the browser. Tested it on chrome 59, seems to stop at around 60.000 for my table.

----------------------------
### Bug report
Table component does not render when entry number exceeded the max call stack size for the browser. Tested it on chrome 59, seems to stop at around 60.000 for my table.
#### Tradeshift UI version affected
v8.1.6

#### Expected Behavior
Render the table
#### Actual Behavior
Does not render
#### Steps to reproduce
Create table with 65000 entries for example
#### Screenshots (optional)
![screen shot 2017-07-28 at 11 45 18](https://user-images.githubusercontent.com/820822/28712546-d930a126-738b-11e7-8e01-c331d696f26d.png)

---------------------------

### Feature request
> Use the `enhancement` label

**Comment by wiredearp** [comment] 2017-07-28 11:28
This appears to be an exact duplicate of https://github.com/Tradeshift/tradeshift-ui/issues/326, although that other team managed to squeeze in about 200.000 rows before the callstack was exceeded.

:confused:  I am (again) not sure that the Table should be expected to handle this many rows on the client side, since it will at some point make searching and sorting extremely slow (and slower in IE and even slower on a mobile phone). That is why the Table can also be configured to run in a "serverside" mode where the pages are rendered one at a time and the Pager is configured manually. I suggest that @upphiminn resort to this option, since we would in any case not have time to optimize the Table in the foreseeable future (even if we decide that this is the best option).

**Closed by wiredearp** 2017-07-28 11:28 UTC
Labels: duplicate
