### ISSUE TITLE
[CompanyCard] Images not loading correctly in the Tradeshift UI card for Win7 IE11

### ISSUE THREAD

**Issue by Krisblast** [Tradeshift/tradeshift-ui#667] opened 2018-10-15 12:09 UTC
**Describe the bug**
The images in TS UI Card doesn't load correctly in the Support Launcher for Win7 IE11. The button itself works (clicking on the card), but the card doesn't render for some reason

**To reproduce**
Go to the Support Launcher in Win7 IE11

**Expected behavior**
The card should display the different image logos

 - OS: [Win7]
 - Browser: [IE]
 - Version: [11]

<img width="1289" alt="screen shot 2018-10-15 at 13 03 44" src="https://user-images.githubusercontent.com/2438028/46950053-c2a9c800-d083-11e8-8286-8307ea96e49f.png">

Notes: 

It works correctly in IE10 and in IE11 on Win10.

**Comment by sampi** [comment] 2018-10-15 12:45
seems to be related to https://github.com/Tradeshift/tradeshift-ui/issues/499
Windows 10 is not affected, only Windows 7.
I can reproduce on http://ui.tradeshift.com/v10/dist/components/cards/companycard.html so React is not to blame this time.

**Comment by sampi** [comment] 2018-10-15 14:29
Fix is in review - https://github.com/Tradeshift/tradeshift-ui/pull/668

**Comment by sampi** [comment] 2018-10-16 10:54
Fixed in https://github.com/Tradeshift/tradeshift-ui/releases/tag/v10.1.1

**Closed** 2018-10-17 08:51 UTC
Labels: issue: bug
