### ISSUE TITLE
Docs site - sidebar content not shown and topbar runs away (iPhone X)

### ISSUE THREAD

**Issue by tstapleton** [Tradeshift/tradeshift-ui#441] opened 2017-11-13 19:03 UTC
#### Tradeshift UI version affected
v9.2.0 (whatever is in the docs site)

#### Expected Behavior

Clicking on the sidebar shows menu items. And topbar doesn’t go away. 

#### Actual Behavior

See video. I clicked on the hamburger icon in the topbar at the beginning, which made the screen go blank. 

#### Steps to reproduce

IPhone X and Safari. Load docs site. 

#### Video

https://www.dropbox.com/s/bvui4tx7dnpmbco/File%20Nov%2013%2C%2010%2058%2026%20AM.mp4?dl=0

**Comment by wiredearp** [comment] 2017-11-15 12:59
The menu should be fixed already on the `10.x` branch, by the way, but that of course doesn't help anyone browsing the website on mobile Safari just yet.

The TopBar is not supposed to go away. It is supposed to always linger just beyond the top of the screen so that it reappears as soon as you start to scroll back up. It uses some kind of weirdly sticky positioning.

**Comment by wiredearp** [comment] 2018-02-12 12:33
@tstapleton I'm still confused about the problem with the TopBar, even after watching the video again. The issue title claims that "TopBar runs away" while the bug description states that "TopBar doesn’t go away", that seems contradictory to mee. In the video, I see a little bit of both behaviors; and the intended behavior is indeed that the TopBar should scroll away as the user scroll down, but that it should snap back into place as soon as he begins to scroll up. This does sort of seem to work on the video, except there is a problem with *clipping* of the TopBar, which sometimes get so bad that you cannot see the TopBar at all, but this bug is (to my knowledge) unfixable.

Note that the TopBar is the purple thing on the top. Below this there is a TabBar, the light gray bar, except is has no tabs in the screenshot 😞 Unlike the TopBar, the TabBar is never supposed to exit the screen and become completely hidden, it is only supposed to scroll to the top of the viewport and then stay *fixed* here (so that the user can always see the tabs).

The question is then, why is the TabBar visible when there are no tabs ❓ but I'm still not clear on this whole problem with the TopBars observed versus expected (versus intended) behavior.

**Comment by tstapleton** [comment] 2018-02-12 19:56
> The issue title claims that "TopBar runs away" while the bug description states that "TopBar doesn’t go away", that seems contradictory to me

the latter part was under expected behavior, the former was about what i saw.

> The question is then, why is the TabBar visible when there are no tabs

i caused that. don't need to worry about it.

> which sometimes get so bad that you cannot see the TopBar at all, but this bug is (to my knowledge) unfixable

_unfixable_? i'm able to trigger it rather easily on my phone.

**Comment by wiredearp** [comment] 2018-02-13 13:01
Yes, it is easily reproducible but unfortunately not (to my knowledge) fixable. What you see is the nothingness that exist beyond the viewport and we would probably need to abandon the whole iframe setup to get rid of this effect (of the Apple patented "bouncy drag"), ot at least that is what I concluded some many many years ago when I first saw it. We could of course look at it again, specifically on @kaumac's iPhone, but I can't promise that we can fix it. The best I could come up with (back then) was to change the color of the white nothingness using a combination of sketchy hacks 😞

**Comment by wiredearp** [comment] 2018-02-15 10:00
Right. So there really is a bug: The iOS bouncy effect can mysteriously "overbounce" the header out of the viewport so that it doesn't correctly track the `scrollTop` of the `Main` element 😞

**Comment by tynandebold** [comment] 2019-01-10 09:49
I can't reproduce this on an iPhone X when looking at the docs site for v12. It seems to have been fixed in this version. Since this issue is under the umbrella of the `tradeshift-ui@12.0.x` milestone, we shouldn't worry about it.

I've uncovered another issue though, wherein the `toolbar-icon` takes the place of the mobile-menu icon. We should address that here.

![screen shot 2019-01-10 at 10 48 32](https://user-images.githubusercontent.com/16869061/50960318-68bf6f80-14c5-11e9-9c9f-4dfd7d8bc906.png)

**Comment by tstapleton** [comment] 2019-01-10 15:38
Confirmed, sidebar is shown and topbar looks good on v12. 

Did you happen to click on the company card component? It does a little dance 💃🕺

https://www.dropbox.com/s/9lnupszlngz88di/tradeshift-UI-company-card.MP4?dl=0

**Comment by tynandebold** [comment] 2019-01-11 09:41
Yes, I saw that. Too funny. That's part of the problem I listed in my previous comment. Aiming to fix today.

**Comment by tynandebold** [comment] 2019-01-11 12:07
Fixed with pull #723

**Closed by tynandebold** 2019-01-11 12:07 UTC
Labels: issue: bug
