### ISSUE TITLE
[Tabel UI] Checkboxes cells are not align with the rows on resize to smaller resolutions

### ISSUE THREAD

**Issue by MirelaPaun** [Tradeshift/tradeshift-ui#343] opened 2017-08-04 13:06 UTC
Choose the section that applies to you and use the template to help us figure out how we can help you.

----------------------------
### Bug report
> Use the `bug` label

#### Tradeshift UI version affected
v7.0.0

#### Expected Behavior
Checkboxes cells should be align with the rows on all resolutions.
#### Actual Behavior
Checkboxes cells are not align with the rows on some smaller resolutions (for example: laptop resolution 1440x900).

#### Steps to reproduce
Display table with some rows and checkboxes and view the table on different windows sizes.

#### Screenshots (optional)
![issue-ui-table](https://user-images.githubusercontent.com/28289435/28969748-9188cd96-792e-11e7-81ee-0bfa9a22f31d.png)
![not-issue-ui-table](https://user-images.githubusercontent.com/28289435/28969747-9186cd84-792e-11e7-9eb4-3012bf2ea76d.png)

**Comment by lloydhumphreys** [comment] 2017-08-04 13:11
Could you add some simplified stylesheet so JMO can try and reproduce? :)

**Comment by MirelaPaun** [comment] 2017-08-04 13:17
Just create a table and add a `<br>` in a cell in the `<p>` tag, something like this: 
```<td id="key329946725-cell-0-0" class="border-left-none border-right-none" data-index="0" style="width: 80px;"><div class="ts-table-cell"><p>Goods<br>Receipt
</p></div></td>``` and it should be easier to reproduce.

**Comment by wiredearp** [comment] 2017-09-07 13:30
OK, @MirelaPaun, I believe that this is probably caused by

1. A misconfiguration of the Table where column `wrap` is not applied
2. A bug that causes the Table to look like it was configured correctly (!)

Alright. As mentioned in http://ui.tradeshift.com/#components/table/layouting.html, you must specify the `wrap` property on any column in order for the cells to wrap text into multiple lines (and you have multiline text in your table). One reason for this is precisely so that the Table doesn't measure the `height` of the cells on each layout update, which causes "repaint" and is therefore a costly procedure for the browser. Without the `wrap` property, the Table will assume that all the rows are standard height, even if they are obviously not, and that would explain why the selection row remains on standard height.

:information_source: I think you can fix the bug straight away if you specify `wrap: true` on the columns that contains multiline cells.

Now, normally you would also only be able to see the first line if you forget to `wrap` the column. The other lines would be hidden by `overflow: hidden`. This problem would under normal conditions lead you to (read the documentation and then) specify `wrap` on the column. But as a side-effect of the image in the first column, you can see all the (two) lines in your cells, even without column `wrap`. Because the `overflow` doesn't crop the text, you have no chance of figuring all this out!

So it's really a bug in the way we have implemented images in the Table.

We will make sure that all cells, even the image cell, becomes cropped to a single (standard) line height if the associated column is not set to `wrap`. And then we'll make a bigger issue of out this in the documentation. But tell us first: Did the suggested fix work?

**Comment by MirelaPaun** [comment] 2017-09-08 08:39
Thank you @wiredearp for your answer.

I added `wrap: true` on the `DocumentID` and `Amount` columns but the table looks like this: 
![checkbox_big_space](https://user-images.githubusercontent.com/28289435/30202574-906e2b9e-9487-11e7-90b5-52d22f1988f7.png)

I have a big space because in `DocumentID` cell I inserted 2 `<p>`, one `<p>` for `document type` and one `<p>` for `date`. I did this because I had different styles for `document type` and `date` in that cell and I didn't find other solution for different styles in the same table cell.

To fix the big space from `DocumentID` column, I have to remove the `margin` from that `<p>`, something like: `.document-id .ts-table-cell p { margin: 0px; }` . Removing that `margin`, my bug is fixed:
![checkbox_fixed](https://user-images.githubusercontent.com/28289435/30202772-489c1082-9488-11e7-8e5c-bfefe2a35745.png)

What do you think about this fix?

**Comment by wiredearp** [comment] 2017-09-08 10:25
Just to be clear: You can then confirm that the cells in the (first) selection-column are aligned correctly with the other cells - also in smaller resolutions - when you specify `wrap` on at least once column?

About the `<p>` elements: According to our calculations, there should only be multiple `<p>` in the cells when the markdown contains at least two `\n\n` newline characters. If you only enter one `\n` newline, the content should be rendered with a `<br>` instead and so your CSS modification is not needed, not that there is anything wrong with it [1]

[1] I think in general it's always OK to remove margins with zero `0` because that means that we are free to add a default margin. This way, the components margin becomes a consistent `22px` whenever it should have a margin; and also a consistent `0px` whenever it should not have a margin. If we don't add this default margin, it will end up with an inconsistent margin of `33px` or `10px` or `25px` because the apps will try to add it themselves; and sometimes using a padding instead of a margin (which doesn't "collapse vertically" and thus becomes even more inconsistent when the number of components increases). CC @dsp and @bomouridsen with regards to the Netflix layout strategy.

**Comment by MirelaPaun** [comment] 2017-09-08 12:07
Yes, I can confirm that the cells from checkbox column are aligned correctly when using `wrap: true` on `DocumentID` column. I tested on my desktop resolution and in chrome mobile emulator and it works. 

Regarding the `<p>` elements, it's true that I use `\n\n` for `DocumentID` column because I want 2 `<p>` elements there and that's why I need to have `margin: 0px`.

**Comment by sampi** [comment] 2018-08-20 12:57
Can't be reproduced. Closing.

**Closed by sampi** 2018-08-20 12:57 UTC
Labels: issue: bug
