### ISSUE TITLE
[Table] UI Table select checkbox lead to the table jumping up and down

### ISSUE THREAD

**Issue by USTC-Han** [Tradeshift/tradeshift-ui#785] opened 2019-05-13 09:05 UTC
**Describe the bug**
Table Bug(ts.ui):
When I toggle the checkbox on the page, if i move the scroll bar to the bottom, the table will jump up and down.The bug effects some applications like Tradeshift.FapiaoIssue.

![ts-ui-scroll](https://user-images.githubusercontent.com/38212028/57608498-9e718380-759f-11e9-8c94-acc796968501.gif)

**To reproduce**
http://ui.tradeshift.com/v12/#components/table/demo.html

**Expected behavior**
when i toggle the checkbox on the page, the table component will not render again.

**Framework usage**
If you're using another framework besides ts.ui include the name and version here. [e.g. React v16.5.0]

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: chrome
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by zdlm** [comment] 2019-06-26 07:38
It is not a bug. Because you select the item in the bottom. we render the dom and need to scroll down to where you select the item. So it need to scroll up to down. We won't fix right now. Unless more and more user complain it.

**Closed** 2019-06-26 07:39 UTC
Labels: issue: wontfix
