### ISSUE TITLE
[Modal] StatusBar does not autohide when empty

### ISSUE THREAD

**Issue by tudorminator** [Tradeshift/tradeshift-ui#632] opened 2018-08-27 08:22 UTC
#### Tradeshift UI version affected
v10.0.25

#### Expected Behavior
StatusBar should hide when using the `modal.buttons().clear()` to remove all the buttons, just like the `Footer` component.

#### Actual Behavior
The empty StatusBar remains visible.

#### Steps to reproduce
Use the docs example to create a modal with a button displayed in the StatusBar.

From a Slack discussion with Daniel Spitzer: https://tradeshift.slack.com/archives/C02TX8JJ7/p1535116853000100?thread_ts=1535112263.000100&cid=C02TX8JJ7

>I see that in the code, once you do anything to enable a `Footer` inside a `Modal`, there is no way to turn it off.  
>The only workaround I can find now is this:

```
ts.ui.get('#my-modal', modal => {
    modal.dom.q('footer', ts.ui.StatusBarSpirit).hide();

    // To undo this, you can do the reverse:
    // modal.dom.q('footer', ts.ui.StatusBarSpirit).show();
});
```

>The problem with this, is that you have to manually `show()` the `Footer` if you want it to come back.  
>Also, once the `StatusBarSpirit` becomes `FooterBarSpirit` or something similar, the code will break.

**Comment by lloydhumphreys** [comment] 2019-01-15 12:37
Duplicate of #700

**Closed** 2019-02-22 09:55 UTC
Labels: tag: enhancement
